name: secrets-deployment

on:
  push:
    branches:
      - main

      
jobs:
  run-tests:
    # if: false # this will cause the job to be skipped - delete to enable
    name: run-tests
    runs-on: ubuntu-latest
    # implement me
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          

      - name: Testing
        run: |
          export PYTHONPATH=$(pwd)
          pytest
          flake8